version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
    restart: unless-stopped

  # Web App
  web-app:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    container_name: web-app
    volumes:
      - ./web-app:/app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
    networks:
      - app-network
    restart: unless-stopped

  # Machine Learning Client
  ml-client:
    build:
      context: ./machine-learning-client
      dockerfile: Dockerfile
    container_name: ml-client
    volumes:
      - ./machine-learning-client:/app
    depends_on:
      - mongodb
      - web-app
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: